name: CI Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test-backend_db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: set up docker compose 
        run:  docker/setup-buildx-action@v2

      - name: run docker compose 
        run:  docker-compose -f docker-compose.yml up -d

      - name: test_database
        run: docker exec db_server mysqladmin ping -h localhost

      - name: test_backend 
        run: docker exec web curl  -f localhost:5000/health
      
      - name: Shut down containers
        run: docker-compose down
